/*
 *	M A P I T A G S . H
 *
 *	Property tag definitions for standard properties of MAPI
 *	objects.
 *
 *	The following ranges should be used for all property IDs. Note that
 *	property IDs for objects other than messages and recipients should
 *	all fall in the range 0x3000 to 0x3FFF:
 *
 *	From	To		Kind of property
 *	--------------------------------
 *	0001	0BFF	MAPI_defined envelope property
 *	0C00	0DFF	MAPI_defined per-recipient property
 *	0E00	0FFF	MAPI_defined non-transmittable property
 *	1000	2FFF	MAPI_defined message content property
 *
 *	3000	3FFF	MAPI_defined property (usually not message or recipient)
 *
 *	4000	57FF	Transport-defined envelope property
 *	5800	5FFF	Transport-defined per-recipient property
 *	6000	65FF	User-defined non-transmittable property
 *	6600	67FF	Provider-defined internal non-transmittable property
 *	6800	7BFF	Message class-defined content property
 *	7C00	7FFF	Message class-defined non-transmittable
 *					property
 *
 *	8000	FFFE	User-defined Name-to-id mapped property
 *
 *	The 3000-3FFF range is further subdivided as follows:
 *
 *	From	To		Kind of property
 *	--------------------------------
 *	3000	33FF	Common property such as display name, entry ID
 *	3400	35FF	Message store object
 *	3600	36FF	Folder or AB container
 *	3700	38FF	Attachment
 *	3900	39FF	Address book object
 *	3A00	3BFF	Mail user
 *	3C00	3CFF	Distribution list
 *	3D00	3DFF	Profile section
 *	3E00	3FFF	Status object
 *
 *  Copyright (c) 2009 Microsoft Corporation. All Rights Reserved.
 */

#ifndef	MAPITAGS_H
#define	MAPITAGS_H

#if _MSC_VER > 1000
#pragma once
#endif

/* Determine if a property is transmittable. */

#define FIsTransmittable(ulPropTag) \
	((PROP_ID (ulPropTag) <  (ULONG)0x0E00) || \
	(PROP_ID (ulPropTag)  >= (ULONG)0x8000) || \
	((PROP_ID (ulPropTag) >= (ULONG)0x1000) && (PROP_ID (ulPropTag) < (ULONG)0x6000)) || \
	((PROP_ID (ulPropTag) >= (ULONG)0x6800) && (PROP_ID (ulPropTag) < (ULONG)0x7C00)))

/*
 *	Message envelope properties
 */

#define PR_ACKNOWLEDGEMENT_MODE						MAKE_SCODE(0, 0x0001, PT_LONG)
#define PR_ALTERNATE_RECIPIENT_ALLOWED				MAKE_SCODE(0, 0x0002, PT_BOOLEAN)
#define PR_AUTHORIZING_USERS						MAKE_SCODE(0, 0x0003, PT_BINARY)
#define PR_AUTO_FORWARD_COMMENT						MAKE_SCODE(0, 0x0004, PT_TSTRING)
#define PR_AUTO_FORWARD_COMMENT_W					MAKE_SCODE(0, 0x0004, PT_UNICODE)
#define PR_AUTO_FORWARD_COMMENT_A					MAKE_SCODE(0, 0x0004, PT_STRING8)
#define PR_AUTO_FORWARDED							MAKE_SCODE(0, 0x0005, PT_BOOLEAN)
#define PR_CONTENT_CONFIDENTIALITY_ALGORITHM_ID		MAKE_SCODE(0, 0x0006, PT_BINARY)
#define PR_CONTENT_CORRELATOR						MAKE_SCODE(0, 0x0007, PT_BINARY)
#define PR_CONTENT_IDENTIFIER						MAKE_SCODE(0, 0x0008, PT_TSTRING)
#define PR_CONTENT_IDENTIFIER_W						MAKE_SCODE(0, 0x0008, PT_UNICODE)
#define PR_CONTENT_IDENTIFIER_A						MAKE_SCODE(0, 0x0008, PT_STRING8)
#define PR_CONTENT_LENGTH							MAKE_SCODE(0, 0x0009, PT_LONG)
#define PR_CONTENT_RETURN_REQUESTED					MAKE_SCODE(0, 0x000A, PT_BOOLEAN)



#define PR_CONVERSATION_KEY							MAKE_SCODE(0, 0x000B, PT_BINARY)

#define PR_CONVERSION_EITS							MAKE_SCODE(0, 0x000C, PT_BINARY)
#define PR_CONVERSION_WITH_LOSS_PROHIBITED			MAKE_SCODE(0, 0x000D, PT_BOOLEAN)
#define PR_CONVERTED_EITS							MAKE_SCODE(0, 0x000E, PT_BINARY)
#define PR_DEFERRED_DELIVERY_TIME					MAKE_SCODE(0, 0x000F, PT_SYSTIME)
#define PR_DELIVER_TIME								MAKE_SCODE(0, 0x0010, PT_SYSTIME)
#define PR_DISCARD_REASON							MAKE_SCODE(0, 0x0011, PT_LONG)
#define PR_DISCLOSURE_OF_RECIPIENTS					MAKE_SCODE(0, 0x0012, PT_BOOLEAN)
#define PR_DL_EXPANSION_HISTORY						MAKE_SCODE(0, 0x0013, PT_BINARY)
#define PR_DL_EXPANSION_PROHIBITED					MAKE_SCODE(0, 0x0014, PT_BOOLEAN)
#define PR_EXPIRY_TIME								MAKE_SCODE(0, 0x0015, PT_SYSTIME)
#define PR_IMPLICIT_CONVERSION_PROHIBITED			MAKE_SCODE(0, 0x0016, PT_BOOLEAN)
#define PR_IMPORTANCE								MAKE_SCODE(0, 0x0017, PT_LONG)
#define PR_IPM_ID									MAKE_SCODE(0, 0x0018, PT_BINARY)
#define PR_LATEST_DELIVERY_TIME						MAKE_SCODE(0, 0x0019, PT_SYSTIME)
#define PR_MESSAGE_CLASS							MAKE_SCODE(0, 0x001A, PT_TSTRING)
#define PR_MESSAGE_CLASS_W							MAKE_SCODE(0, 0x001A, PT_UNICODE)
#define PR_MESSAGE_CLASS_A							MAKE_SCODE(0, 0x001A, PT_STRING8)
#define PR_MESSAGE_DELIVERY_ID						MAKE_SCODE(0, 0x001B, PT_BINARY)





#define PR_MESSAGE_SECURITY_LABEL					MAKE_SCODE(0, 0x001E, PT_BINARY)
#define PR_OBSOLETED_IPMS							MAKE_SCODE(0, 0x001F, PT_BINARY)
#define PR_ORIGINALLY_INTENDED_RECIPIENT_NAME		MAKE_SCODE(0, 0x0020, PT_BINARY)
#define PR_ORIGINAL_EITS							MAKE_SCODE(0, 0x0021, PT_BINARY)
#define PR_ORIGINATOR_CERTIFICATE					MAKE_SCODE(0, 0x0022, PT_BINARY)
#define PR_ORIGINATOR_DELIVERY_REPORT_REQUESTED		MAKE_SCODE(0, 0x0023, PT_BOOLEAN)
#define PR_ORIGINATOR_RETURN_ADDRESS				MAKE_SCODE(0, 0x0024, PT_BINARY)



#define PR_PARENT_KEY								MAKE_SCODE(0, 0x0025, PT_BINARY)
#define PR_PRIORITY									MAKE_SCODE(0, 0x0026, PT_LONG)



#define PR_ORIGIN_CHECK								MAKE_SCODE(0, 0x0027, PT_BINARY)
#define PR_PROOF_OF_SUBMISSION_REQUESTED			MAKE_SCODE(0, 0x0028, PT_BOOLEAN)
#define PR_READ_RECEIPT_REQUESTED					MAKE_SCODE(0, 0x0029, PT_BOOLEAN)
#define PR_RECEIPT_TIME								MAKE_SCODE(0, 0x002A, PT_SYSTIME)
#define PR_RECIPIENT_REASSIGNMENT_PROHIBITED		MAKE_SCODE(0, 0x002B, PT_BOOLEAN)
#define PR_REDIRECTION_HISTORY						MAKE_SCODE(0, 0x002C, PT_BINARY)
#define PR_RELATED_IPMS								MAKE_SCODE(0, 0x002D, PT_BINARY)
#define PR_ORIGINAL_SENSITIVITY						MAKE_SCODE(0, 0x002E, PT_LONG)
#define	PR_LANGUAGES								MAKE_SCODE(0, 0x002F, PT_TSTRING)
#define	PR_LANGUAGES_W								MAKE_SCODE(0, 0x002F, PT_UNICODE)
#define	PR_LANGUAGES_A								MAKE_SCODE(0, 0x002F, PT_STRING8)
#define PR_REPLY_TIME								MAKE_SCODE(0, 0x0030, PT_SYSTIME)
#define PR_REPORT_TAG								MAKE_SCODE(0, 0x0031, PT_BINARY)
#define PR_REPORT_TIME								MAKE_SCODE(0, 0x0032, PT_SYSTIME)
#define PR_RETURNED_IPM								MAKE_SCODE(0, 0x0033, PT_BOOLEAN)
#define PR_SECURITY									MAKE_SCODE(0, 0x0034, PT_LONG)
#define	PR_INCOMPLETE_COPY							MAKE_SCODE(0, 0x0035, PT_BOOLEAN)
#define PR_SENSITIVITY								MAKE_SCODE(0, 0x0036, PT_LONG)
#define PR_SUBJECT									MAKE_SCODE(0, 0x0037, PT_TSTRING)
#define PR_SUBJECT_W								MAKE_SCODE(0, 0x0037, PT_UNICODE)
#define PR_SUBJECT_A								MAKE_SCODE(0, 0x0037, PT_STRING8)
#define PR_SUBJECT_IPM								MAKE_SCODE(0, 0x0038, PT_BINARY)
#define PR_CLIENT_SUBMIT_TIME						MAKE_SCODE(0, 0x0039, PT_SYSTIME)
#define PR_REPORT_NAME								MAKE_SCODE(0, 0x003A, PT_TSTRING)
#define PR_REPORT_NAME_W							MAKE_SCODE(0, 0x003A, PT_UNICODE)
#define PR_REPORT_NAME_A							MAKE_SCODE(0, 0x003A, PT_STRING8)
#define	PR_SENT_REPRESENTING_SEARCH_KEY				MAKE_SCODE(0, 0x003B, PT_BINARY)
#define PR_X400_CONTENT_TYPE						MAKE_SCODE(0, 0x003C, PT_BINARY)
#define PR_SUBJECT_PREFIX							MAKE_SCODE(0, 0x003D, PT_TSTRING)
#define PR_SUBJECT_PREFIX_W	 						MAKE_SCODE(0, 0x003D, PT_UNICODE)
#define PR_SUBJECT_PREFIX_A	 						MAKE_SCODE(0, 0x003D, PT_STRING8)
#define PR_NON_RECEIPT_REASON						MAKE_SCODE(0, 0x003E, PT_LONG)
#define PR_RECEIVED_BY_ENTRYID						MAKE_SCODE(0, 0x003F, PT_BINARY)
#define PR_RECEIVED_BY_NAME							MAKE_SCODE(0, 0x0040, PT_TSTRING)
#define PR_RECEIVED_BY_NAME_W						MAKE_SCODE(0, 0x0040, PT_UNICODE)
#define PR_RECEIVED_BY_NAME_A						MAKE_SCODE(0, 0x0040, PT_STRING8)
#define	PR_SENT_REPRESENTING_ENTRYID				MAKE_SCODE(0, 0x0041, PT_BINARY)
#define PR_SENT_REPRESENTING_NAME					MAKE_SCODE(0, 0x0042, PT_TSTRING)
#define PR_SENT_REPRESENTING_NAME_W					MAKE_SCODE(0, 0x0042, PT_UNICODE)
#define PR_SENT_REPRESENTING_NAME_A					MAKE_SCODE(0, 0x0042, PT_STRING8)
#define PR_RCVD_REPRESENTING_ENTRYID				MAKE_SCODE(0, 0x0043, PT_BINARY)
#define PR_RCVD_REPRESENTING_NAME					MAKE_SCODE(0, 0x0044, PT_TSTRING)
#define PR_RCVD_REPRESENTING_NAME_W					MAKE_SCODE(0, 0x0044, PT_UNICODE)
#define PR_RCVD_REPRESENTING_NAME_A					MAKE_SCODE(0, 0x0044, PT_STRING8)
#define PR_REPORT_ENTRYID							MAKE_SCODE(0, 0x0045, PT_BINARY)
#define PR_READ_RECEIPT_ENTRYID						MAKE_SCODE(0, 0x0046, PT_BINARY)
#define PR_MESSAGE_SUBMISSION_ID					MAKE_SCODE(0, 0x0047, PT_BINARY)
#define PR_PROVIDER_SUBMIT_TIME						MAKE_SCODE(0, 0x0048, PT_SYSTIME)
#define	PR_ORIGINAL_SUBJECT							MAKE_SCODE(0, 0x0049, PT_TSTRING)
#define	PR_ORIGINAL_SUBJECT_W						MAKE_SCODE(0, 0x0049, PT_UNICODE)
#define	PR_ORIGINAL_SUBJECT_A						MAKE_SCODE(0, 0x0049, PT_STRING8)
#define PR_DISC_VAL									MAKE_SCODE(0, 0x004A, PT_BOOLEAN)
#define PR_ORIG_MESSAGE_CLASS						MAKE_SCODE(0, 0x004B, PT_TSTRING)
#define PR_ORIG_MESSAGE_CLASS_W						MAKE_SCODE(0, 0x004B, PT_UNICODE)
#define PR_ORIG_MESSAGE_CLASS_A						MAKE_SCODE(0, 0x004B, PT_STRING8)
#define PR_ORIGINAL_AUTHOR_ENTRYID					MAKE_SCODE(0, 0x004C, PT_BINARY)
#define PR_ORIGINAL_AUTHOR_NAME						MAKE_SCODE(0, 0x004D, PT_TSTRING)
#define PR_ORIGINAL_AUTHOR_NAME_W					MAKE_SCODE(0, 0x004D, PT_UNICODE)
#define PR_ORIGINAL_AUTHOR_NAME_A					MAKE_SCODE(0, 0x004D, PT_STRING8)
#define PR_ORIGINAL_SUBMIT_TIME						MAKE_SCODE(0, 0x004E, PT_SYSTIME)
#define PR_REPLY_RECIPIENT_ENTRIES					MAKE_SCODE(0, 0x004F, PT_BINARY)
#define PR_REPLY_RECIPIENT_NAMES					MAKE_SCODE(0, 0x0050, PT_TSTRING)
#define PR_REPLY_RECIPIENT_NAMES_W					MAKE_SCODE(0, 0x0050, PT_UNICODE)
#define PR_REPLY_RECIPIENT_NAMES_A					MAKE_SCODE(0, 0x0050, PT_STRING8)

#define PR_RECEIVED_BY_SEARCH_KEY					MAKE_SCODE(0, 0x0051, PT_BINARY)
#define PR_RCVD_REPRESENTING_SEARCH_KEY				MAKE_SCODE(0, 0x0052, PT_BINARY)
#define PR_READ_RECEIPT_SEARCH_KEY					MAKE_SCODE(0, 0x0053, PT_BINARY)
#define PR_REPORT_SEARCH_KEY						MAKE_SCODE(0, 0x0054, PT_BINARY)
#define	PR_ORIGINAL_DELIVERY_TIME					MAKE_SCODE(0, 0x0055, PT_SYSTIME)
#define PR_ORIGINAL_AUTHOR_SEARCH_KEY				MAKE_SCODE(0, 0x0056, PT_BINARY)

#define	PR_MESSAGE_TO_ME							MAKE_SCODE(0, 0x0057, PT_BOOLEAN)
#define	PR_MESSAGE_CC_ME							MAKE_SCODE(0, 0x0058, PT_BOOLEAN)
#define	PR_MESSAGE_RECIP_ME							MAKE_SCODE(0, 0x0059, PT_BOOLEAN)

#define PR_ORIGINAL_SENDER_NAME						MAKE_SCODE(0, 0x005A, PT_TSTRING)
#define PR_ORIGINAL_SENDER_NAME_W					MAKE_SCODE(0, 0x005A, PT_UNICODE)
#define PR_ORIGINAL_SENDER_NAME_A					MAKE_SCODE(0, 0x005A, PT_STRING8)
#define	PR_ORIGINAL_SENDER_ENTRYID					MAKE_SCODE(0, 0x005B, PT_BINARY)
#define	PR_ORIGINAL_SENDER_SEARCH_KEY				MAKE_SCODE(0, 0x005C, PT_BINARY)
#define PR_ORIGINAL_SENT_REPRESENTING_NAME			MAKE_SCODE(0, 0x005D, PT_TSTRING)
#define PR_ORIGINAL_SENT_REPRESENTING_NAME_W		MAKE_SCODE(0, 0x005D, PT_UNICODE)
#define PR_ORIGINAL_SENT_REPRESENTING_NAME_A		MAKE_SCODE(0, 0x005D, PT_STRING8)
#define	PR_ORIGINAL_SENT_REPRESENTING_ENTRYID		MAKE_SCODE(0, 0x005E, PT_BINARY)
#define	PR_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY	MAKE_SCODE(0, 0x005F, PT_BINARY)

#define PR_START_DATE								MAKE_SCODE(0, 0x0060, PT_SYSTIME)
#define PR_END_DATE									MAKE_SCODE(0, 0x0061, PT_SYSTIME)
#define PR_OWNER_APPT_ID							MAKE_SCODE(0, 0x0062, PT_LONG)
#define PR_RESPONSE_REQUESTED						MAKE_SCODE(0, 0x0063, PT_BOOLEAN)

#define PR_SENT_REPRESENTING_ADDRTYPE				MAKE_SCODE(0, 0x0064, PT_TSTRING)
#define PR_SENT_REPRESENTING_ADDRTYPE_W				MAKE_SCODE(0, 0x0064, PT_UNICODE)
#define PR_SENT_REPRESENTING_ADDRTYPE_A				MAKE_SCODE(0, 0x0064, PT_STRING8)
#define PR_SENT_REPRESENTING_EMAIL_ADDRESS			MAKE_SCODE(0, 0x0065, PT_TSTRING)
#define PR_SENT_REPRESENTING_EMAIL_ADDRESS_W		MAKE_SCODE(0, 0x0065, PT_UNICODE)
#define PR_SENT_REPRESENTING_EMAIL_ADDRESS_A		MAKE_SCODE(0, 0x0065, PT_STRING8)

#define PR_ORIGINAL_SENDER_ADDRTYPE					MAKE_SCODE(0, 0x0066, PT_TSTRING)
#define PR_ORIGINAL_SENDER_ADDRTYPE_W				MAKE_SCODE(0, 0x0066, PT_UNICODE)
#define PR_ORIGINAL_SENDER_ADDRTYPE_A				MAKE_SCODE(0, 0x0066, PT_STRING8)
#define PR_ORIGINAL_SENDER_EMAIL_ADDRESS			MAKE_SCODE(0, 0x0067, PT_TSTRING)
#define PR_ORIGINAL_SENDER_EMAIL_ADDRESS_W			MAKE_SCODE(0, 0x0067, PT_UNICODE)
#define PR_ORIGINAL_SENDER_EMAIL_ADDRESS_A			MAKE_SCODE(0, 0x0067, PT_STRING8)

#define PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE		MAKE_SCODE(0, 0x0068, PT_TSTRING)
#define PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_W	MAKE_SCODE(0, 0x0068, PT_UNICODE)
#define PR_ORIGINAL_SENT_REPRESENTING_ADDRTYPE_A	MAKE_SCODE(0, 0x0068, PT_STRING8)
#define PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS	MAKE_SCODE(0, 0x0069, PT_TSTRING)
#define PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_W	MAKE_SCODE(0, 0x0069, PT_UNICODE)
#define PR_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS_A	MAKE_SCODE(0, 0x0069, PT_STRING8)

#define	PR_CONVERSATION_TOPIC						MAKE_SCODE(0, 0x0070, PT_TSTRING)
#define	PR_CONVERSATION_TOPIC_W						MAKE_SCODE(0, 0x0070, PT_UNICODE)
#define	PR_CONVERSATION_TOPIC_A						MAKE_SCODE(0, 0x0070, PT_STRING8)
#define	PR_CONVERSATION_INDEX						MAKE_SCODE(0, 0x0071, PT_BINARY)

#define PR_ORIGINAL_DISPLAY_BCC						MAKE_SCODE(0, 0x0072, PT_TSTRING)
#define PR_ORIGINAL_DISPLAY_BCC_W					MAKE_SCODE(0, 0x0072, PT_UNICODE)
#define PR_ORIGINAL_DISPLAY_BCC_A					MAKE_SCODE(0, 0x0072, PT_STRING8)
#define PR_ORIGINAL_DISPLAY_CC						MAKE_SCODE(0, 0x0073, PT_TSTRING)
#define PR_ORIGINAL_DISPLAY_CC_W					MAKE_SCODE(0, 0x0073, PT_UNICODE)
#define PR_ORIGINAL_DISPLAY_CC_A					MAKE_SCODE(0, 0x0073, PT_STRING8)
#define PR_ORIGINAL_DISPLAY_TO						MAKE_SCODE(0, 0x0074, PT_TSTRING)
#define PR_ORIGINAL_DISPLAY_TO_W					MAKE_SCODE(0, 0x0074, PT_UNICODE)
#define PR_ORIGINAL_DISPLAY_TO_A					MAKE_SCODE(0, 0x0074, PT_STRING8)

#define PR_RECEIVED_BY_ADDRTYPE						MAKE_SCODE(0, 0x0075, PT_TSTRING)
#define PR_RECEIVED_BY_ADDRTYPE_W					MAKE_SCODE(0, 0x0075, PT_UNICODE)
#define PR_RECEIVED_BY_ADDRTYPE_A					MAKE_SCODE(0, 0x0075, PT_STRING8)
#define	PR_RECEIVED_BY_EMAIL_ADDRESS				MAKE_SCODE(0, 0x0076, PT_TSTRING)
#define	PR_RECEIVED_BY_EMAIL_ADDRESS_W				MAKE_SCODE(0, 0x0076, PT_UNICODE)
#define	PR_RECEIVED_BY_EMAIL_ADDRESS_A				MAKE_SCODE(0, 0x0076, PT_STRING8)

#define PR_RCVD_REPRESENTING_ADDRTYPE				MAKE_SCODE(0, 0x0077, PT_TSTRING)
#define PR_RCVD_REPRESENTING_ADDRTYPE_W				MAKE_SCODE(0, 0x0077, PT_UNICODE)
#define PR_RCVD_REPRESENTING_ADDRTYPE_A				MAKE_SCODE(0, 0x0077, PT_STRING8)
#define PR_RCVD_REPRESENTING_EMAIL_ADDRESS			MAKE_SCODE(0, 0x0078, PT_TSTRING)
#define PR_RCVD_REPRESENTING_EMAIL_ADDRESS_W		MAKE_SCODE(0, 0x0078, PT_UNICODE)
#define PR_RCVD_REPRESENTING_EMAIL_ADDRESS_A		MAKE_SCODE(0, 0x0078, PT_STRING8)

#define PR_ORIGINAL_AUTHOR_ADDRTYPE					MAKE_SCODE(0, 0x0079, PT_TSTRING)
#define PR_ORIGINAL_AUTHOR_ADDRTYPE_W				MAKE_SCODE(0, 0x0079, PT_UNICODE)
#define PR_ORIGINAL_AUTHOR_ADDRTYPE_A				MAKE_SCODE(0, 0x0079, PT_STRING8)
#define PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS			MAKE_SCODE(0, 0x007A, PT_TSTRING)
#define PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_W			MAKE_SCODE(0, 0x007A, PT_UNICODE)
#define PR_ORIGINAL_AUTHOR_EMAIL_ADDRESS_A			MAKE_SCODE(0, 0x007A, PT_STRING8)

#define PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE		MAKE_SCODE(0, 0x007B, PT_TSTRING)
#define PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_W		MAKE_SCODE(0, 0x007B, PT_UNICODE)
#define PR_ORIGINALLY_INTENDED_RECIP_ADDRTYPE_A		MAKE_SCODE(0, 0x007B, PT_STRING8)
#define PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS	MAKE_SCODE(0, 0x007C, PT_TSTRING)
#define PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_W	MAKE_SCODE(0, 0x007C, PT_UNICODE)
#define PR_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS_A	MAKE_SCODE(0, 0x007C, PT_STRING8)

#define PR_TRANSPORT_MESSAGE_HEADERS				MAKE_SCODE(0, 0x007D, PT_TSTRING)
#define PR_TRANSPORT_MESSAGE_HEADERS_W				MAKE_SCODE(0, 0x007D, PT_UNICODE)
#define PR_TRANSPORT_MESSAGE_HEADERS_A				MAKE_SCODE(0, 0x007D, PT_STRING8)

#define PR_DELEGATION								MAKE_SCODE(0, 0x007E, PT_BINARY)

#define PR_TNEF_CORRELATION_KEY						MAKE_SCODE(0, 0x007F, PT_BINARY)



/*
 *	Message content properties
 */

#define PR_BODY										MAKE_SCODE(0, 0x1000, PT_TSTRING)
#define PR_BODY_W									MAKE_SCODE(0, 0x1000, PT_UNICODE)
#define PR_BODY_A									MAKE_SCODE(0, 0x1000, PT_STRING8)
#define PR_REPORT_TEXT								MAKE_SCODE(0, 0x1001, PT_TSTRING)
#define PR_REPORT_TEXT_W							MAKE_SCODE(0, 0x1001, PT_UNICODE)
#define PR_REPORT_TEXT_A							MAKE_SCODE(0, 0x1001, PT_STRING8)
#define PR_ORIGINATOR_AND_DL_EXPANSION_HISTORY		MAKE_SCODE(0, 0x1002, PT_BINARY)
#define PR_REPORTING_DL_NAME						MAKE_SCODE(0, 0x1003, PT_BINARY)
#define PR_REPORTING_MTA_CERTIFICATE				MAKE_SCODE(0, 0x1004, PT_BINARY)

/*  Removed PR_REPORT_ORIGIN_AUTHENTICATION_CHECK with DCR 3865, use PR_ORIGIN_CHECK */

#define PR_RTF_SYNC_BODY_CRC						MAKE_SCODE(0, 0x1006, PT_LONG)
#define PR_RTF_SYNC_BODY_COUNT						MAKE_SCODE(0, 0x1007, PT_LONG)
#define PR_RTF_SYNC_BODY_TAG						MAKE_SCODE(0, 0x1008, PT_TSTRING)
#define PR_RTF_SYNC_BODY_TAG_W						MAKE_SCODE(0, 0x1008, PT_UNICODE)
#define PR_RTF_SYNC_BODY_TAG_A						MAKE_SCODE(0, 0x1008, PT_STRING8)
#define PR_RTF_COMPRESSED							MAKE_SCODE(0, 0x1009, PT_BINARY)
#define PR_RTF_SYNC_PREFIX_COUNT					MAKE_SCODE(0, 0x1010, PT_LONG)
#define PR_RTF_SYNC_TRAILING_COUNT					MAKE_SCODE(0, 0x1011, PT_LONG)
#define PR_ORIGINALLY_INTENDED_RECIP_ENTRYID		MAKE_SCODE(0, 0x1012, PT_BINARY)

/*
 *  Reserved 0x1100-0x1200
 */


/*
 *	Message recipient properties
 */

#define PR_CONTENT_INTEGRITY_CHECK					MAKE_SCODE(0, 0x0C00, PT_BINARY)
#define PR_EXPLICIT_CONVERSION						MAKE_SCODE(0, 0x0C01, PT_LONG)
#define PR_IPM_RETURN_REQUESTED						MAKE_SCODE(0, 0x0C02, PT_BOOLEAN)
#define PR_MESSAGE_TOKEN							MAKE_SCODE(0, 0x0C03, PT_BINARY)
#define PR_NDR_REASON_CODE							MAKE_SCODE(0, 0x0C04, PT_LONG)
#define PR_NDR_DIAG_CODE							MAKE_SCODE(0, 0x0C05, PT_LONG)
#define PR_NON_RECEIPT_NOTIFICATION_REQUESTED		MAKE_SCODE(0, 0x0C06, PT_BOOLEAN)
#define PR_DELIVERY_POINT							MAKE_SCODE(0, 0x0C07, PT_LONG)

#define PR_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED	MAKE_SCODE(0, 0x0C08, PT_BOOLEAN)
#define PR_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT	MAKE_SCODE(0, 0x0C09, PT_BINARY)
#define PR_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY	MAKE_SCODE(0, 0x0C0A, PT_BOOLEAN)
#define PR_PHYSICAL_DELIVERY_MODE					MAKE_SCODE(0, 0x0C0B, PT_LONG)
#define PR_PHYSICAL_DELIVERY_REPORT_REQUEST			MAKE_SCODE(0, 0x0C0C, PT_LONG)
#define PR_PHYSICAL_FORWARDING_ADDRESS				MAKE_SCODE(0, 0x0C0D, PT_BINARY)
#define PR_PHYSICAL_FORWARDING_ADDRESS_REQUESTED	MAKE_SCODE(0, 0x0C0E, PT_BOOLEAN)
#define PR_PHYSICAL_FORWARDING_PROHIBITED			MAKE_SCODE(0, 0x0C0F, PT_BOOLEAN)
#define PR_PHYSICAL_RENDITION_ATTRIBUTES			MAKE_SCODE(0, 0x0C10, PT_BINARY)
#define PR_PROOF_OF_DELIVERY						MAKE_SCODE(0, 0x0C11, PT_BINARY)
#define PR_PROOF_OF_DELIVERY_REQUESTED				MAKE_SCODE(0, 0x0C12, PT_BOOLEAN)
#define PR_RECIPIENT_CERTIFICATE					MAKE_SCODE(0, 0x0C13, PT_BINARY)
#define PR_RECIPIENT_NUMBER_FOR_ADVICE				MAKE_SCODE(0, 0x0C14, PT_TSTRING)
#define PR_RECIPIENT_NUMBER_FOR_ADVICE_W			MAKE_SCODE(0, 0x0C14, PT_UNICODE)
#define PR_RECIPIENT_NUMBER_FOR_ADVICE_A			MAKE_SCODE(0, 0x0C14, PT_STRING8)
#define PR_RECIPIENT_TYPE							MAKE_SCODE(0, 0x0C15, PT_LONG)
#define PR_REGISTERED_MAIL_TYPE						MAKE_SCODE(0, 0x0C16, PT_LONG)
#define PR_REPLY_REQUESTED							MAKE_SCODE(0, 0x0C17, PT_BOOLEAN)
#define PR_REQUESTED_DELIVERY_METHOD				MAKE_SCODE(0, 0x0C18, PT_LONG)
#define PR_SENDER_ENTRYID							MAKE_SCODE(0, 0x0C19, PT_BINARY)
#define PR_SENDER_NAME								MAKE_SCODE(0, 0x0C1A, PT_TSTRING)
#define PR_SENDER_NAME_W							MAKE_SCODE(0, 0x0C1A, PT_UNICODE)
#define PR_SENDER_NAME_A							MAKE_SCODE(0, 0x0C1A, PT_STRING8)
#define PR_SUPPLEMENTARY_INFO						MAKE_SCODE(0, 0x0C1B, PT_TSTRING)
#define PR_SUPPLEMENTARY_INFO_W						MAKE_SCODE(0, 0x0C1B, PT_UNICODE)
#define PR_SUPPLEMENTARY_INFO_A						MAKE_SCODE(0, 0x0C1B, PT_STRING8)
#define PR_TYPE_OF_MTS_USER							MAKE_SCODE(0, 0x0C1C, PT_LONG)
#define PR_SENDER_SEARCH_KEY						MAKE_SCODE(0, 0x0C1D, PT_BINARY)
#define PR_SENDER_ADDRTYPE							MAKE_SCODE(0, 0x0C1E, PT_TSTRING)
#define PR_SENDER_ADDRTYPE_W						MAKE_SCODE(0, 0x0C1E, PT_UNICODE)
#define PR_SENDER_ADDRTYPE_A						MAKE_SCODE(0, 0x0C1E, PT_STRING8)
#define PR_SENDER_EMAIL_ADDRESS						MAKE_SCODE(0, 0x0C1F, PT_TSTRING)
#define PR_SENDER_EMAIL_ADDRESS_W					MAKE_SCODE(0, 0x0C1F, PT_UNICODE)
#define PR_SENDER_EMAIL_ADDRESS_A					MAKE_SCODE(0, 0x0C1F, PT_STRING8)

/*
 *	Message non-transmittable properties
 */

/*
 * The two tags, PR_MESSAGE_RECIPIENTS and PR_MESSAGE_ATTACHMENTS,
 * are to be used in the exclude list passed to
 * IMessage::CopyTo when the caller wants either the recipients or attachments
 * of the message to not get copied.  It is also used in the ProblemArray
 * return from IMessage::CopyTo when an error is encountered copying them
 */

#define PR_CURRENT_VERSION							MAKE_SCODE(0, 0x0E00, PT_I8)
#define PR_DELETE_AFTER_SUBMIT						MAKE_SCODE(0, 0x0E01, PT_BOOLEAN)
#define PR_DISPLAY_BCC								MAKE_SCODE(0, 0x0E02, PT_TSTRING)
#define PR_DISPLAY_BCC_W							MAKE_SCODE(0, 0x0E02, PT_UNICODE)
#define PR_DISPLAY_BCC_A							MAKE_SCODE(0, 0x0E02, PT_STRING8)
#define PR_DISPLAY_CC								MAKE_SCODE(0, 0x0E03, PT_TSTRING)
#define PR_DISPLAY_CC_W								MAKE_SCODE(0, 0x0E03, PT_UNICODE)
#define PR_DISPLAY_CC_A								MAKE_SCODE(0, 0x0E03, PT_STRING8)
#define PR_DISPLAY_TO								MAKE_SCODE(0, 0x0E04, PT_TSTRING)
#define PR_DISPLAY_TO_W								MAKE_SCODE(0, 0x0E04, PT_UNICODE)
#define PR_DISPLAY_TO_A								MAKE_SCODE(0, 0x0E04, PT_STRING8)
#define PR_PARENT_DISPLAY							MAKE_SCODE(0, 0x0E05, PT_TSTRING)
#define PR_PARENT_DISPLAY_W							MAKE_SCODE(0, 0x0E05, PT_UNICODE)
#define PR_PARENT_DISPLAY_A							MAKE_SCODE(0, 0x0E05, PT_STRING8)
#define PR_MESSAGE_DELIVERY_TIME					MAKE_SCODE(0, 0x0E06, PT_SYSTIME)
#define PR_MESSAGE_FLAGS							MAKE_SCODE(0, 0x0E07, PT_LONG)
#define PR_MESSAGE_SIZE								MAKE_SCODE(0, 0x0E08, PT_LONG)
#define PR_PARENT_ENTRYID							MAKE_SCODE(0, 0x0E09, PT_BINARY)
#define PR_SENTMAIL_ENTRYID							MAKE_SCODE(0, 0x0E0A, PT_BINARY)
#define PR_CORRELATE								MAKE_SCODE(0, 0x0E0C, PT_BOOLEAN)
#define PR_CORRELATE_MTSID							MAKE_SCODE(0, 0x0E0D, PT_BINARY)
#define PR_DISCRETE_VALUES							MAKE_SCODE(0, 0x0E0E, PT_BOOLEAN)
#define PR_RESPONSIBILITY							MAKE_SCODE(0, 0x0E0F, PT_BOOLEAN)
#define	PR_SPOOLER_STATUS							MAKE_SCODE(0, 0x0E10, PT_LONG)
#define	PR_TRANSPORT_STATUS							MAKE_SCODE(0, 0x0E11, PT_LONG)
#define PR_MESSAGE_RECIPIENTS						MAKE_SCODE(0, 0x0E12, PT_OBJECT)
#define PR_MESSAGE_ATTACHMENTS						MAKE_SCODE(0, 0x0E13, PT_OBJECT)
#define PR_SUBMIT_FLAGS								MAKE_SCODE(0, 0x0E14, PT_LONG)
#define PR_RECIPIENT_STATUS							MAKE_SCODE(0, 0x0E15, PT_LONG)
#define	PR_TRANSPORT_KEY							MAKE_SCODE(0, 0x0E16, PT_LONG)
#define PR_MSG_STATUS								MAKE_SCODE(0, 0x0E17, PT_LONG)
#define	PR_MESSAGE_DOWNLOAD_TIME					MAKE_SCODE(0, 0x0E18, PT_LONG)
#define PR_CREATION_VERSION							MAKE_SCODE(0, 0x0E19, PT_I8)
#define PR_MODIFY_VERSION							MAKE_SCODE(0, 0x0E1A, PT_I8)
#define PR_HASATTACH								MAKE_SCODE(0, 0x0E1B, PT_BOOLEAN)
#define PR_BODY_CRC									MAKE_SCODE(0, 0x0E1C, PT_LONG)
#define PR_NORMALIZED_SUBJECT						MAKE_SCODE(0, 0x0E1D, PT_TSTRING)
#define PR_NORMALIZED_SUBJECT_W						MAKE_SCODE(0, 0x0E1D, PT_UNICODE)
#define PR_NORMALIZED_SUBJECT_A						MAKE_SCODE(0, 0x0E1D, PT_STRING8)
#define PR_RTF_IN_SYNC								MAKE_SCODE(0, 0x0E1F, PT_BOOLEAN)
#define PR_ATTACH_SIZE								MAKE_SCODE(0, 0x0E20, PT_LONG)
#define PR_ATTACH_NUM								MAKE_SCODE(0, 0x0E21, PT_LONG)
#define PR_PREPROCESS								MAKE_SCODE(0, 0x0E22, PT_BOOLEAN)

/* PR_ORIGINAL_DISPLAY_TO, _CC, and _BCC moved to transmittible range 03/09/95 */

#define PR_ORIGINATING_MTA_CERTIFICATE				MAKE_SCODE(0, 0x0E25, PT_BINARY)
#define PR_PROOF_OF_SUBMISSION						MAKE_SCODE(0, 0x0E26, PT_BINARY)


/*
 * The range of non-message and non-recipient property IDs (0x3000 - 0x3FFF) is
 * further broken down into ranges to make assigning new property IDs easier.
 *
 *	From	To		Kind of property
 *	--------------------------------
 *	3000	32FF	MAPI_defined common property
 *	3200	33FF	MAPI_defined form property
 *	3400	35FF	MAPI_defined message store property
 *	3600	36FF	MAPI_defined Folder or AB Container property
 *	3700	38FF	MAPI_defined attachment property
 *	3900	39FF	MAPI_defined address book property
 *	3A00	3BFF	MAPI_defined mailuser property
 *	3C00	3CFF	MAPI_defined DistList property
 *	3D00	3DFF	MAPI_defined Profile Section property
 *	3E00	3EFF	MAPI_defined Status property
 *	3F00	3FFF	MAPI_defined display table property
 */

/*
 *	Properties common to numerous MAPI objects.
 *
 *	Those properties that can appear on messages are in the
 *	non-transmittable range for messages. They start at the high
 *	end of that range and work down.
 *
 *	Properties that never appear on messages are defined in the common
 *	property range (see above).
 */

/*
 * properties that are common to multiple objects (including message objects)
 * -- these ids are in the non-transmittable range
 */

#define PR_ENTRYID									MAKE_SCODE(0, 0x0FFF, PT_BINARY)
#define PR_OBJECT_TYPE								MAKE_SCODE(0, 0x0FFE, PT_LONG)
#define PR_ICON										MAKE_SCODE(0, 0x0FFD, PT_BINARY)
#define PR_MINI_ICON								MAKE_SCODE(0, 0x0FFC, PT_BINARY)
#define PR_STORE_ENTRYID							MAKE_SCODE(0, 0x0FFB, PT_BINARY)
#define PR_STORE_RECORD_KEY							MAKE_SCODE(0, 0x0FFA, PT_BINARY)
#define PR_RECORD_KEY								MAKE_SCODE(0, 0x0FF9, PT_BINARY)
#define PR_MAPPING_SIGNATURE						MAKE_SCODE(0, 0x0FF8, PT_BINARY)
#define PR_ACCESS_LEVEL								MAKE_SCODE(0, 0x0FF7, PT_LONG)
#define PR_INSTANCE_KEY								MAKE_SCODE(0, 0x0FF6, PT_BINARY)
#define PR_ROW_TYPE									MAKE_SCODE(0, 0x0FF5, PT_LONG)
#define PR_ACCESS									MAKE_SCODE(0, 0x0FF4, PT_LONG)

/*
 * properties that are common to multiple objects (usually not including message objects)
 * -- these ids are in the transmittable range
 */

#define PR_ROWID									MAKE_SCODE(0, 0x3000, PT_LONG)
#define PR_DISPLAY_NAME								MAKE_SCODE(0, 0x3001, PT_TSTRING)
#define PR_DISPLAY_NAME_W							MAKE_SCODE(0, 0x3001, PT_UNICODE)
#define PR_DISPLAY_NAME_A							MAKE_SCODE(0, 0x3001, PT_STRING8)
#define PR_ADDRTYPE									MAKE_SCODE(0, 0x3002, PT_TSTRING)
#define PR_ADDRTYPE_W								MAKE_SCODE(0, 0x3002, PT_UNICODE)
#define PR_ADDRTYPE_A								MAKE_SCODE(0, 0x3002, PT_STRING8)
#define PR_EMAIL_ADDRESS							MAKE_SCODE(0, 0x3003, PT_TSTRING)
#define PR_EMAIL_ADDRESS_W							MAKE_SCODE(0, 0x3003, PT_UNICODE)
#define PR_EMAIL_ADDRESS_A							MAKE_SCODE(0, 0x3003, PT_STRING8)
#define PR_COMMENT									MAKE_SCODE(0, 0x3004, PT_TSTRING)
#define PR_COMMENT_W								MAKE_SCODE(0, 0x3004, PT_UNICODE)
#define PR_COMMENT_A								MAKE_SCODE(0, 0x3004, PT_STRING8)
#define PR_DEPTH									MAKE_SCODE(0, 0x3005, PT_LONG)
#define PR_PROVIDER_DISPLAY							MAKE_SCODE(0, 0x3006, PT_TSTRING)
#define PR_PROVIDER_DISPLAY_W						MAKE_SCODE(0, 0x3006, PT_UNICODE)
#define PR_PROVIDER_DISPLAY_A						MAKE_SCODE(0, 0x3006, PT_STRING8)
#define PR_CREATION_TIME							MAKE_SCODE(0, 0x3007, PT_SYSTIME)
#define PR_LAST_MODIFICATION_TIME					MAKE_SCODE(0, 0x3008, PT_SYSTIME)
#define PR_RESOURCE_FLAGS							MAKE_SCODE(0, 0x3009, PT_LONG)
#define PR_PROVIDER_DLL_NAME						MAKE_SCODE(0, 0x300A, PT_TSTRING)
#define PR_PROVIDER_DLL_NAME_W						MAKE_SCODE(0, 0x300A, PT_UNICODE)
#define PR_PROVIDER_DLL_NAME_A						MAKE_SCODE(0, 0x300A, PT_STRING8)
#define PR_SEARCH_KEY								MAKE_SCODE(0, 0x300B, PT_BINARY)
#define PR_PROVIDER_UID								MAKE_SCODE(0, 0x300C, PT_BINARY)
#define PR_PROVIDER_ORDINAL							MAKE_SCODE(0, 0x300D, PT_LONG)

/*
 *  MAPI Form properties
 */
#define PR_FORM_VERSION								MAKE_SCODE(0, 0x3301, PT_TSTRING)
#define PR_FORM_VERSION_W							MAKE_SCODE(0, 0x3301, PT_UNICODE)
#define PR_FORM_VERSION_A							MAKE_SCODE(0, 0x3301, PT_STRING8)
#define PR_FORM_CLSID								MAKE_SCODE(0, 0x3302, PT_CLSID)
#define PR_FORM_CONTACT_NAME						MAKE_SCODE(0, 0x3303, PT_TSTRING)
#define PR_FORM_CONTACT_NAME_W						MAKE_SCODE(0, 0x3303, PT_UNICODE)
#define PR_FORM_CONTACT_NAME_A						MAKE_SCODE(0, 0x3303, PT_STRING8)
#define PR_FORM_CATEGORY							MAKE_SCODE(0, 0x3304, PT_TSTRING)
#define PR_FORM_CATEGORY_W							MAKE_SCODE(0, 0x3304, PT_UNICODE)
#define PR_FORM_CATEGORY_A							MAKE_SCODE(0, 0x3304, PT_STRING8)
#define PR_FORM_CATEGORY_SUB						MAKE_SCODE(0, 0x3305, PT_TSTRING)
#define PR_FORM_CATEGORY_SUB_W						MAKE_SCODE(0, 0x3305, PT_UNICODE)
#define PR_FORM_CATEGORY_SUB_A						MAKE_SCODE(0, 0x3305, PT_STRING8)
#define PR_FORM_HOST_MAP							MAKE_SCODE(0, 0x3306, PT_MV_LONG)
#define PR_FORM_HIDDEN								MAKE_SCODE(0, 0x3307, PT_BOOLEAN)
#define PR_FORM_DESIGNER_NAME						MAKE_SCODE(0, 0x3308, PT_TSTRING)
#define PR_FORM_DESIGNER_NAME_W						MAKE_SCODE(0, 0x3308, PT_UNICODE)
#define PR_FORM_DESIGNER_NAME_A						MAKE_SCODE(0, 0x3308, PT_STRING8)
#define PR_FORM_DESIGNER_GUID						MAKE_SCODE(0, 0x3309, PT_CLSID)
#define PR_FORM_MESSAGE_BEHAVIOR					MAKE_SCODE(0, 0x330A, PT_LONG)

/*
 *	Message store properties
 */

#define PR_DEFAULT_STORE							MAKE_SCODE(0, 0x3400, PT_BOOLEAN)
#define PR_STORE_SUPPORT_MASK						MAKE_SCODE(0, 0x340D, PT_LONG)
#define PR_STORE_STATE								MAKE_SCODE(0, 0x340E, PT_LONG)

#define PR_IPM_SUBTREE_SEARCH_KEY					MAKE_SCODE(0, 0x3410, PT_BINARY)
#define PR_IPM_OUTBOX_SEARCH_KEY					MAKE_SCODE(0, 0x3411, PT_BINARY)
#define PR_IPM_WASTEBASKET_SEARCH_KEY				MAKE_SCODE(0, 0x3412, PT_BINARY)
#define PR_IPM_SENTMAIL_SEARCH_KEY					MAKE_SCODE(0, 0x3413, PT_BINARY)
#define PR_MDB_PROVIDER								MAKE_SCODE(0, 0x3414, PT_BINARY)
#define PR_RECEIVE_FOLDER_SETTINGS					MAKE_SCODE(0, 0x3415, PT_OBJECT)

#define PR_VALID_FOLDER_MASK						MAKE_SCODE(0, 0x35DF, PT_LONG)
#define PR_IPM_SUBTREE_ENTRYID						MAKE_SCODE(0, 0x35E0, PT_BINARY)

#define PR_IPM_OUTBOX_ENTRYID						MAKE_SCODE(0, 0x35E2, PT_BINARY)
#define PR_IPM_WASTEBASKET_ENTRYID					MAKE_SCODE(0, 0x35E3, PT_BINARY)
#define PR_IPM_SENTMAIL_ENTRYID						MAKE_SCODE(0, 0x35E4, PT_BINARY)
#define PR_VIEWS_ENTRYID							MAKE_SCODE(0, 0x35E5, PT_BINARY)
#define PR_COMMON_VIEWS_ENTRYID						MAKE_SCODE(0, 0x35E6, PT_BINARY)
#define PR_FINDER_ENTRYID							MAKE_SCODE(0, 0x35E7, PT_BINARY)

/* Proptags 0x35E8-0x35FF reserved for folders "guaranteed" by PR_VALID_FOLDER_MASK */


/*
 *	Folder and AB Container properties
 */

#define PR_CONTAINER_FLAGS							MAKE_SCODE(0, 0x3600, PT_LONG)
#define PR_FOLDER_TYPE								MAKE_SCODE(0, 0x3601, PT_LONG)
#define PR_CONTENT_COUNT							MAKE_SCODE(0, 0x3602, PT_LONG)
#define PR_CONTENT_UNREAD							MAKE_SCODE(0, 0x3603, PT_LONG)
#define PR_CREATE_TEMPLATES							MAKE_SCODE(0, 0x3604, PT_OBJECT)
#define PR_DETAILS_TABLE							MAKE_SCODE(0, 0x3605, PT_OBJECT)
#define PR_SEARCH									MAKE_SCODE(0, 0x3607, PT_OBJECT)
#define PR_SELECTABLE								MAKE_SCODE(0, 0x3609, PT_BOOLEAN)
#define PR_SUBFOLDERS								MAKE_SCODE(0, 0x360A, PT_BOOLEAN)
#define PR_STATUS									MAKE_SCODE(0, 0x360B, PT_LONG)
#define PR_ANR										MAKE_SCODE(0, 0x360C, PT_TSTRING)
#define PR_ANR_W									MAKE_SCODE(0, 0x360C, PT_UNICODE)
#define PR_ANR_A									MAKE_SCODE(0, 0x360C, PT_STRING8)
#define PR_CONTENTS_SORT_ORDER						MAKE_SCODE(0, 0x360D, PT_MV_LONG)
#define PR_CONTAINER_HIERARCHY						MAKE_SCODE(0, 0x360E, PT_OBJECT)
#define PR_CONTAINER_CONTENTS						MAKE_SCODE(0, 0x360F, PT_OBJECT)
#define PR_FOLDER_ASSOCIATED_CONTENTS				MAKE_SCODE(0, 0x3610, PT_OBJECT)
#define PR_DEF_CREATE_DL							MAKE_SCODE(0, 0x3611, PT_BINARY)
#define PR_DEF_CREATE_MAILUSER						MAKE_SCODE(0, 0x3612, PT_BINARY)
#define	PR_CONTAINER_CLASS							MAKE_SCODE(0, 0x3613, PT_TSTRING)
#define	PR_CONTAINER_CLASS_W						MAKE_SCODE(0, 0x3613, PT_UNICODE)
#define	PR_CONTAINER_CLASS_A						MAKE_SCODE(0, 0x3613, PT_STRING8)
#define	PR_CONTAINER_MODIFY_VERSION					MAKE_SCODE(0, 0x3614, PT_I8)
#define PR_AB_PROVIDER_ID							MAKE_SCODE(0, 0x3615, PT_BINARY)
#define PR_DEFAULT_VIEW_ENTRYID						MAKE_SCODE(0, 0x3616, PT_BINARY)
#define	PR_ASSOC_CONTENT_COUNT						MAKE_SCODE(0, 0x3617, PT_LONG)

/* Reserved 0x36C0-0x36FF */

/*
 *	Attachment properties
 */

#define PR_ATTACHMENT_X400_PARAMETERS				MAKE_SCODE(0, 0x3700, PT_BINARY)
#define PR_ATTACH_DATA_OBJ							MAKE_SCODE(0, 0x3701, PT_OBJECT)
#define PR_ATTACH_DATA_BIN							MAKE_SCODE(0, 0x3701, PT_BINARY)
#define PR_ATTACH_ENCODING							MAKE_SCODE(0, 0x3702, PT_BINARY)
#define PR_ATTACH_EXTENSION							MAKE_SCODE(0, 0x3703, PT_TSTRING)
#define PR_ATTACH_EXTENSION_W						MAKE_SCODE(0, 0x3703, PT_UNICODE)
#define PR_ATTACH_EXTENSION_A						MAKE_SCODE(0, 0x3703, PT_STRING8)
#define PR_ATTACH_FILENAME							MAKE_SCODE(0, 0x3704, PT_TSTRING)
#define PR_ATTACH_FILENAME_W						MAKE_SCODE(0, 0x3704, PT_UNICODE)
#define PR_ATTACH_FILENAME_A						MAKE_SCODE(0, 0x3704, PT_STRING8)
#define PR_ATTACH_METHOD							MAKE_SCODE(0, 0x3705, PT_LONG)
#define PR_ATTACH_LONG_FILENAME	 					MAKE_SCODE(0, 0x3707, PT_TSTRING)
#define PR_ATTACH_LONG_FILENAME_W					MAKE_SCODE(0, 0x3707, PT_UNICODE)
#define PR_ATTACH_LONG_FILENAME_A					MAKE_SCODE(0, 0x3707, PT_STRING8)
#define PR_ATTACH_PATHNAME							MAKE_SCODE(0, 0x3708, PT_TSTRING)
#define PR_ATTACH_PATHNAME_W						MAKE_SCODE(0, 0x3708, PT_UNICODE)
#define PR_ATTACH_PATHNAME_A						MAKE_SCODE(0, 0x3708, PT_STRING8)
#define PR_ATTACH_RENDERING							MAKE_SCODE(0, 0x3709, PT_BINARY)
#define PR_ATTACH_TAG								MAKE_SCODE(0, 0x370A, PT_BINARY)
#define PR_RENDERING_POSITION						MAKE_SCODE(0, 0x370B, PT_LONG)
#define PR_ATTACH_TRANSPORT_NAME					MAKE_SCODE(0, 0x370C, PT_TSTRING)
#define PR_ATTACH_TRANSPORT_NAME_W					MAKE_SCODE(0, 0x370C, PT_UNICODE)
#define PR_ATTACH_TRANSPORT_NAME_A					MAKE_SCODE(0, 0x370C, PT_STRING8)
#define PR_ATTACH_LONG_PATHNAME	 					MAKE_SCODE(0, 0x370D, PT_TSTRING)
#define PR_ATTACH_LONG_PATHNAME_W					MAKE_SCODE(0, 0x370D, PT_UNICODE)
#define PR_ATTACH_LONG_PATHNAME_A					MAKE_SCODE(0, 0x370D, PT_STRING8)
#define PR_ATTACH_MIME_TAG							MAKE_SCODE(0, 0x370E, PT_TSTRING)
#define PR_ATTACH_MIME_TAG_W						MAKE_SCODE(0, 0x370E, PT_UNICODE)
#define PR_ATTACH_MIME_TAG_A						MAKE_SCODE(0, 0x370E, PT_STRING8)
#define	PR_ATTACH_ADDITIONAL_INFO					MAKE_SCODE(0, 0x370F, PT_BINARY)

/*
 *  AB Object properties
 */

#define PR_DISPLAY_TYPE								MAKE_SCODE(0, 0x3900, PT_LONG)
#define PR_TEMPLATEID								MAKE_SCODE(0, 0x3902, PT_BINARY)
#define PR_PRIMARY_CAPABILITY						MAKE_SCODE(0, 0x3904, PT_BINARY)


/*
 *	Mail user properties
 */
#define PR_7BIT_DISPLAY_NAME						MAKE_SCODE(0, 0x39FF, PT_STRING8)
#define PR_ACCOUNT									MAKE_SCODE(0, 0x3A00, PT_TSTRING)
#define PR_ACCOUNT_W								MAKE_SCODE(0, 0x3A00, PT_UNICODE)
#define PR_ACCOUNT_A								MAKE_SCODE(0, 0x3A00, PT_STRING8)
#define PR_ALTERNATE_RECIPIENT						MAKE_SCODE(0, 0x3A01, PT_BINARY)
#define PR_CALLBACK_TELEPHONE_NUMBER				MAKE_SCODE(0, 0x3A02, PT_TSTRING)
#define PR_CALLBACK_TELEPHONE_NUMBER_W				MAKE_SCODE(0, 0x3A02, PT_UNICODE)
#define PR_CALLBACK_TELEPHONE_NUMBER_A				MAKE_SCODE(0, 0x3A02, PT_STRING8)
#define PR_CONVERSION_PROHIBITED					MAKE_SCODE(0, 0x3A03, PT_BOOLEAN)
#define PR_DISCLOSE_RECIPIENTS						MAKE_SCODE(0, 0x3A04, PT_BOOLEAN)
#define PR_GENERATION								MAKE_SCODE(0, 0x3A05, PT_TSTRING)
#define PR_GENERATION_W								MAKE_SCODE(0, 0x3A05, PT_UNICODE)
#define PR_GENERATION_A								MAKE_SCODE(0, 0x3A05, PT_STRING8)
#define PR_GIVEN_NAME								MAKE_SCODE(0, 0x3A06, PT_TSTRING)
#define PR_GIVEN_NAME_W								MAKE_SCODE(0, 0x3A06, PT_UNICODE)
#define PR_GIVEN_NAME_A								MAKE_SCODE(0, 0x3A06, PT_STRING8)
#define PR_GOVERNMENT_ID_NUMBER						MAKE_SCODE(0, 0x3A07, PT_TSTRING)
#define PR_GOVERNMENT_ID_NUMBER_W					MAKE_SCODE(0, 0x3A07, PT_UNICODE)
#define PR_GOVERNMENT_ID_NUMBER_A					MAKE_SCODE(0, 0x3A07, PT_STRING8)
#define PR_BUSINESS_TELEPHONE_NUMBER				MAKE_SCODE(0, 0x3A08, PT_TSTRING)
#define PR_BUSINESS_TELEPHONE_NUMBER_W				MAKE_SCODE(0, 0x3A08, PT_UNICODE)
#define PR_BUSINESS_TELEPHONE_NUMBER_A				MAKE_SCODE(0, 0x3A08, PT_STRING8)
#define PR_OFFICE_TELEPHONE_NUMBER					PR_BUSINESS_TELEPHONE_NUMBER
#define PR_OFFICE_TELEPHONE_NUMBER_W				PR_BUSINESS_TELEPHONE_NUMBER_W
#define PR_OFFICE_TELEPHONE_NUMBER_A				PR_BUSINESS_TELEPHONE_NUMBER_A
#define PR_HOME_TELEPHONE_NUMBER					MAKE_SCODE(0, 0x3A09, PT_TSTRING)
#define PR_HOME_TELEPHONE_NUMBER_W					MAKE_SCODE(0, 0x3A09, PT_UNICODE)
#define PR_HOME_TELEPHONE_NUMBER_A					MAKE_SCODE(0, 0x3A09, PT_STRING8)
#define PR_INITIALS									MAKE_SCODE(0, 0x3A0A, PT_TSTRING)
#define PR_INITIALS_W								MAKE_SCODE(0, 0x3A0A, PT_UNICODE)
#define PR_INITIALS_A								MAKE_SCODE(0, 0x3A0A, PT_STRING8)
#define PR_KEYWORD									MAKE_SCODE(0, 0x3A0B, PT_TSTRING)
#define PR_KEYWORD_W								MAKE_SCODE(0, 0x3A0B, PT_UNICODE)
#define PR_KEYWORD_A								MAKE_SCODE(0, 0x3A0B, PT_STRING8)
#define PR_LANGUAGE									MAKE_SCODE(0, 0x3A0C, PT_TSTRING)
#define PR_LANGUAGE_W								MAKE_SCODE(0, 0x3A0C, PT_UNICODE)
#define PR_LANGUAGE_A								MAKE_SCODE(0, 0x3A0C, PT_STRING8)
#define PR_LOCATION									MAKE_SCODE(0, 0x3A0D, PT_TSTRING)
#define PR_LOCATION_W								MAKE_SCODE(0, 0x3A0D, PT_UNICODE)
#define PR_LOCATION_A								MAKE_SCODE(0, 0x3A0D, PT_STRING8)
#define PR_MAIL_PERMISSION							MAKE_SCODE(0, 0x3A0E, PT_BOOLEAN)
#define PR_MHS_COMMON_NAME							MAKE_SCODE(0, 0x3A0F, PT_TSTRING)
#define PR_MHS_COMMON_NAME_W						MAKE_SCODE(0, 0x3A0F, PT_UNICODE)
#define PR_MHS_COMMON_NAME_A						MAKE_SCODE(0, 0x3A0F, PT_STRING8)
#define PR_ORGANIZATIONAL_ID_NUMBER					MAKE_SCODE(0, 0x3A10, PT_TSTRING)
#define PR_ORGANIZATIONAL_ID_NUMBER_W				MAKE_SCODE(0, 0x3A10, PT_UNICODE)
#define PR_ORGANIZATIONAL_ID_NUMBER_A				MAKE_SCODE(0, 0x3A10, PT_STRING8)
#define PR_SURNAME									MAKE_SCODE(0, 0x3A11, PT_TSTRING)
#define PR_SURNAME_W								MAKE_SCODE(0, 0x3A11, PT_UNICODE)
#define PR_SURNAME_A								MAKE_SCODE(0, 0x3A11, PT_STRING8)
#define PR_ORIGINAL_ENTRYID							MAKE_SCODE(0, 0x3A12, PT_BINARY)
#define PR_ORIGINAL_DISPLAY_NAME					MAKE_SCODE(0, 0x3A13, PT_TSTRING)
#define PR_ORIGINAL_DISPLAY_NAME_W					MAKE_SCODE(0, 0x3A13, PT_UNICODE)
#define PR_ORIGINAL_DISPLAY_NAME_A					MAKE_SCODE(0, 0x3A13, PT_STRING8)
#define PR_ORIGINAL_SEARCH_KEY						MAKE_SCODE(0, 0x3A14, PT_BINARY)
#define PR_POSTAL_ADDRESS							MAKE_SCODE(0, 0x3A15, PT_TSTRING)
#define PR_POSTAL_ADDRESS_W							MAKE_SCODE(0, 0x3A15, PT_UNICODE)
#define PR_POSTAL_ADDRESS_A							MAKE_SCODE(0, 0x3A15, PT_STRING8)
#define PR_COMPANY_NAME								MAKE_SCODE(0, 0x3A16, PT_TSTRING)
#define PR_COMPANY_NAME_W							MAKE_SCODE(0, 0x3A16, PT_UNICODE)
#define PR_COMPANY_NAME_A							MAKE_SCODE(0, 0x3A16, PT_STRING8)
#define PR_TITLE									MAKE_SCODE(0, 0x3A17, PT_TSTRING)
#define PR_TITLE_W									MAKE_SCODE(0, 0x3A17, PT_UNICODE)
#define PR_TITLE_A									MAKE_SCODE(0, 0x3A17, PT_STRING8)
#define PR_DEPARTMENT_NAME							MAKE_SCODE(0, 0x3A18, PT_TSTRING)
#define PR_DEPARTMENT_NAME_W						MAKE_SCODE(0, 0x3A18, PT_UNICODE)
#define PR_DEPARTMENT_NAME_A						MAKE_SCODE(0, 0x3A18, PT_STRING8)
#define PR_OFFICE_LOCATION							MAKE_SCODE(0, 0x3A19, PT_TSTRING)
#define PR_OFFICE_LOCATION_W						MAKE_SCODE(0, 0x3A19, PT_UNICODE)
#define PR_OFFICE_LOCATION_A						MAKE_SCODE(0, 0x3A19, PT_STRING8)
#define PR_PRIMARY_TELEPHONE_NUMBER					MAKE_SCODE(0, 0x3A1A, PT_TSTRING)
#define PR_PRIMARY_TELEPHONE_NUMBER_W				MAKE_SCODE(0, 0x3A1A, PT_UNICODE)
#define PR_PRIMARY_TELEPHONE_NUMBER_A				MAKE_SCODE(0, 0x3A1A, PT_STRING8)
#define PR_BUSINESS2_TELEPHONE_NUMBER				MAKE_SCODE(0, 0x3A1B, PT_TSTRING)
#define PR_BUSINESS2_TELEPHONE_NUMBER_W				MAKE_SCODE(0, 0x3A1B, PT_UNICODE)
#define PR_BUSINESS2_TELEPHONE_NUMBER_A				MAKE_SCODE(0, 0x3A1B, PT_STRING8)
#define PR_OFFICE2_TELEPHONE_NUMBER					PR_BUSINESS2_TELEPHONE_NUMBER
#define PR_OFFICE2_TELEPHONE_NUMBER_W				PR_BUSINESS2_TELEPHONE_NUMBER_W
#define PR_OFFICE2_TELEPHONE_NUMBER_A				PR_BUSINESS2_TELEPHONE_NUMBER_A
#define PR_MOBILE_TELEPHONE_NUMBER					MAKE_SCODE(0, 0x3A1C, PT_TSTRING)
#define PR_MOBILE_TELEPHONE_NUMBER_W				MAKE_SCODE(0, 0x3A1C, PT_UNICODE)
#define PR_MOBILE_TELEPHONE_NUMBER_A				MAKE_SCODE(0, 0x3A1C, PT_STRING8)
#define PR_CELLULAR_TELEPHONE_NUMBER				PR_MOBILE_TELEPHONE_NUMBER
#define PR_CELLULAR_TELEPHONE_NUMBER_W				PR_MOBILE_TELEPHONE_NUMBER_W
#define PR_CELLULAR_TELEPHONE_NUMBER_A				PR_MOBILE_TELEPHONE_NUMBER_A
#define PR_RADIO_TELEPHONE_NUMBER					MAKE_SCODE(0, 0x3A1D, PT_TSTRING)
#define PR_RADIO_TELEPHONE_NUMBER_W					MAKE_SCODE(0, 0x3A1D, PT_UNICODE)
#define PR_RADIO_TELEPHONE_NUMBER_A					MAKE_SCODE(0, 0x3A1D, PT_STRING8)
#define PR_CAR_TELEPHONE_NUMBER						MAKE_SCODE(0, 0x3A1E, PT_TSTRING)
#define PR_CAR_TELEPHONE_NUMBER_W					MAKE_SCODE(0, 0x3A1E, PT_UNICODE)
#define PR_CAR_TELEPHONE_NUMBER_A					MAKE_SCODE(0, 0x3A1E, PT_STRING8)
#define PR_OTHER_TELEPHONE_NUMBER					MAKE_SCODE(0, 0x3A1F, PT_TSTRING)
#define PR_OTHER_TELEPHONE_NUMBER_W					MAKE_SCODE(0, 0x3A1F, PT_UNICODE)
#define PR_OTHER_TELEPHONE_NUMBER_A					MAKE_SCODE(0, 0x3A1F, PT_STRING8)
#define PR_TRANSMITABLE_DISPLAY_NAME				MAKE_SCODE(0, 0x3A20, PT_TSTRING)
#define PR_TRANSMITABLE_DISPLAY_NAME_W				MAKE_SCODE(0, 0x3A20, PT_UNICODE)
#define PR_TRANSMITABLE_DISPLAY_NAME_A				MAKE_SCODE(0, 0x3A20, PT_STRING8)
#define PR_PAGER_TELEPHONE_NUMBER					MAKE_SCODE(0, 0x3A21, PT_TSTRING)
#define PR_PAGER_TELEPHONE_NUMBER_W					MAKE_SCODE(0, 0x3A21, PT_UNICODE)
#define PR_PAGER_TELEPHONE_NUMBER_A					MAKE_SCODE(0, 0x3A21, PT_STRING8)
#define PR_BEEPER_TELEPHONE_NUMBER					PR_PAGER_TELEPHONE_NUMBER
#define PR_BEEPER_TELEPHONE_NUMBER_W				PR_PAGER_TELEPHONE_NUMBER_W
#define PR_BEEPER_TELEPHONE_NUMBER_A				PR_PAGER_TELEPHONE_NUMBER_A
#define PR_USER_CERTIFICATE							MAKE_SCODE(0, 0x3A22, PT_BINARY)
#define PR_PRIMARY_FAX_NUMBER						MAKE_SCODE(0, 0x3A23, PT_TSTRING)
#define PR_PRIMARY_FAX_NUMBER_W						MAKE_SCODE(0, 0x3A23, PT_UNICODE)
#define PR_PRIMARY_FAX_NUMBER_A						MAKE_SCODE(0, 0x3A23, PT_STRING8)
#define PR_BUSINESS_FAX_NUMBER						MAKE_SCODE(0, 0x3A24, PT_TSTRING)
#define PR_BUSINESS_FAX_NUMBER_W					MAKE_SCODE(0, 0x3A24, PT_UNICODE)
#define PR_BUSINESS_FAX_NUMBER_A					MAKE_SCODE(0, 0x3A24, PT_STRING8)
#define PR_HOME_FAX_NUMBER							MAKE_SCODE(0, 0x3A25, PT_TSTRING)
#define PR_HOME_FAX_NUMBER_W						MAKE_SCODE(0, 0x3A25, PT_UNICODE)
#define PR_HOME_FAX_NUMBER_A						MAKE_SCODE(0, 0x3A25, PT_STRING8)
#define PR_COUNTRY									MAKE_SCODE(0, 0x3A26, PT_TSTRING)
#define PR_COUNTRY_W								MAKE_SCODE(0, 0x3A26, PT_UNICODE)
#define PR_COUNTRY_A								MAKE_SCODE(0, 0x3A26, PT_STRING8)
#define PR_BUSINESS_ADDRESS_COUNTRY					PR_COUNTRY
#define PR_BUSINESS_ADDRESS_COUNTRY_W				PR_COUNTRY_W
#define PR_BUSINESS_ADDRESS_COUNTRY_A				PR_COUNTRY_A

#define PR_LOCALITY									MAKE_SCODE(0, 0x3A27, PT_TSTRING)
#define PR_LOCALITY_W								MAKE_SCODE(0, 0x3A27, PT_UNICODE)
#define PR_LOCALITY_A								MAKE_SCODE(0, 0x3A27, PT_STRING8)
#define PR_BUSINESS_ADDRESS_CITY					PR_LOCALITY
#define PR_BUSINESS_ADDRESS_CITY_W					PR_LOCALITY_W
#define PR_BUSINESS_ADDRESS_CITY_A					PR_LOCALITY_A

#define PR_STATE_OR_PROVINCE						MAKE_SCODE(0, 0x3A28, PT_TSTRING)
#define PR_STATE_OR_PROVINCE_W						MAKE_SCODE(0, 0x3A28, PT_UNICODE)
#define PR_STATE_OR_PROVINCE_A						MAKE_SCODE(0, 0x3A28, PT_STRING8)
#define PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE		PR_STATE_OR_PROVINCE
#define PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE_W		PR_STATE_OR_PROVINCE_W
#define PR_BUSINESS_ADDRESS_STATE_OR_PROVINCE_A		PR_STATE_OR_PROVINCE_A

#define PR_STREET_ADDRESS							MAKE_SCODE(0, 0x3A29, PT_TSTRING)
#define PR_STREET_ADDRESS_W							MAKE_SCODE(0, 0x3A29, PT_UNICODE)
#define PR_STREET_ADDRESS_A							MAKE_SCODE(0, 0x3A29, PT_STRING8)
#define PR_BUSINESS_ADDRESS_STREET					PR_STREET_ADDRESS
#define PR_BUSINESS_ADDRESS_STREET_W				PR_STREET_ADDRESS_W
#define PR_BUSINESS_ADDRESS_STREET_A				PR_STREET_ADDRESS_A

#define PR_POSTAL_CODE								MAKE_SCODE(0, 0x3A2A, PT_TSTRING)
#define PR_POSTAL_CODE_W							MAKE_SCODE(0, 0x3A2A, PT_UNICODE)
#define PR_POSTAL_CODE_A							MAKE_SCODE(0, 0x3A2A, PT_STRING8)
#define PR_BUSINESS_ADDRESS_POSTAL_CODE				PR_POSTAL_CODE
#define PR_BUSINESS_ADDRESS_POSTAL_CODE_W			PR_POSTAL_CODE_W
#define PR_BUSINESS_ADDRESS_POSTAL_CODE_A			PR_POSTAL_CODE_A


#define PR_POST_OFFICE_BOX							MAKE_SCODE(0, 0x3A2B, PT_TSTRING)
#define PR_POST_OFFICE_BOX_W						MAKE_SCODE(0, 0x3A2B, PT_UNICODE)
#define PR_POST_OFFICE_BOX_A						MAKE_SCODE(0, 0x3A2B, PT_STRING8)
#define PR_BUSINESS_ADDRESS_POST_OFFICE_BOX			PR_POST_OFFICE_BOX
#define PR_BUSINESS_ADDRESS_POST_OFFICE_BOX_W		PR_POST_OFFICE_BOX_W
#define PR_BUSINESS_ADDRESS_POST_OFFICE_BOX_A		PR_POST_OFFICE_BOX_A


#define PR_TELEX_NUMBER								MAKE_SCODE(0, 0x3A2C, PT_TSTRING)
#define PR_TELEX_NUMBER_W							MAKE_SCODE(0, 0x3A2C, PT_UNICODE)
#define PR_TELEX_NUMBER_A							MAKE_SCODE(0, 0x3A2C, PT_STRING8)
#define PR_ISDN_NUMBER								MAKE_SCODE(0, 0x3A2D, PT_TSTRING)
#define PR_ISDN_NUMBER_W							MAKE_SCODE(0, 0x3A2D, PT_UNICODE)
#define PR_ISDN_NUMBER_A							MAKE_SCODE(0, 0x3A2D, PT_STRING8)
#define PR_ASSISTANT_TELEPHONE_NUMBER				MAKE_SCODE(0, 0x3A2E, PT_TSTRING)
#define PR_ASSISTANT_TELEPHONE_NUMBER_W				MAKE_SCODE(0, 0x3A2E, PT_UNICODE)
#define PR_ASSISTANT_TELEPHONE_NUMBER_A				MAKE_SCODE(0, 0x3A2E, PT_STRING8)
#define PR_HOME2_TELEPHONE_NUMBER					MAKE_SCODE(0, 0x3A2F, PT_TSTRING)
#define PR_HOME2_TELEPHONE_NUMBER_W					MAKE_SCODE(0, 0x3A2F, PT_UNICODE)
#define PR_HOME2_TELEPHONE_NUMBER_A					MAKE_SCODE(0, 0x3A2F, PT_STRING8)
#define PR_ASSISTANT								MAKE_SCODE(0, 0x3A30, PT_TSTRING)
#define PR_ASSISTANT_W								MAKE_SCODE(0, 0x3A30, PT_UNICODE)
#define PR_ASSISTANT_A								MAKE_SCODE(0, 0x3A30, PT_STRING8)
#define PR_SEND_RICH_INFO							MAKE_SCODE(0, 0x3A40, PT_BOOLEAN)

#define PR_WEDDING_ANNIVERSARY						MAKE_SCODE(0, 0x3A41, PT_SYSTIME)
#define PR_BIRTHDAY									MAKE_SCODE(0, 0x3A42, PT_SYSTIME)


#define PR_HOBBIES									MAKE_SCODE(0, 0x3A43, PT_TSTRING)
#define PR_HOBBIES_W								MAKE_SCODE(0, 0x3A43, PT_UNICODE)
#define PR_HOBBIES_A								MAKE_SCODE(0, 0x3A43, PT_STRING8)

#define PR_MIDDLE_NAME								MAKE_SCODE(0, 0x3A44, PT_TSTRING)
#define PR_MIDDLE_NAME_W							MAKE_SCODE(0, 0x3A44, PT_UNICODE)
#define PR_MIDDLE_NAME_A							MAKE_SCODE(0, 0x3A44, PT_STRING8)

#define PR_DISPLAY_NAME_PREFIX						MAKE_SCODE(0, 0x3A45, PT_TSTRING)
#define PR_DISPLAY_NAME_PREFIX_W					MAKE_SCODE(0, 0x3A45, PT_UNICODE)
#define PR_DISPLAY_NAME_PREFIX_A					MAKE_SCODE(0, 0x3A45, PT_STRING8)

#define PR_PROFESSION								MAKE_SCODE(0, 0x3A46, PT_TSTRING)
#define PR_PROFESSION_W								MAKE_SCODE(0, 0x3A46, PT_UNICODE)
#define PR_PROFESSION_A								MAKE_SCODE(0, 0x3A46, PT_STRING8)

#define PR_PREFERRED_BY_NAME						MAKE_SCODE(0, 0x3A47, PT_TSTRING)
#define PR_PREFERRED_BY_NAME_W						MAKE_SCODE(0, 0x3A47, PT_UNICODE)
#define PR_PREFERRED_BY_NAME_A						MAKE_SCODE(0, 0x3A47, PT_STRING8)

#define PR_SPOUSE_NAME								MAKE_SCODE(0, 0x3A48, PT_TSTRING)
#define PR_SPOUSE_NAME_W							MAKE_SCODE(0, 0x3A48, PT_UNICODE)
#define PR_SPOUSE_NAME_A							MAKE_SCODE(0, 0x3A48, PT_STRING8)

#define PR_COMPUTER_NETWORK_NAME					MAKE_SCODE(0, 0x3A49, PT_TSTRING)
#define PR_COMPUTER_NETWORK_NAME_W					MAKE_SCODE(0, 0x3A49, PT_UNICODE)
#define PR_COMPUTER_NETWORK_NAME_A					MAKE_SCODE(0, 0x3A49, PT_STRING8)

#define PR_CUSTOMER_ID								MAKE_SCODE(0, 0x3A4A, PT_TSTRING)
#define PR_CUSTOMER_ID_W							MAKE_SCODE(0, 0x3A4A, PT_UNICODE)
#define PR_CUSTOMER_ID_A							MAKE_SCODE(0, 0x3A4A, PT_STRING8)

#define PR_TTYTDD_PHONE_NUMBER						MAKE_SCODE(0, 0x3A4B, PT_TSTRING)
#define PR_TTYTDD_PHONE_NUMBER_W					MAKE_SCODE(0, 0x3A4B, PT_UNICODE)
#define PR_TTYTDD_PHONE_NUMBER_A					MAKE_SCODE(0, 0x3A4B, PT_STRING8)

#define PR_FTP_SITE									MAKE_SCODE(0, 0x3A4C, PT_TSTRING)
#define PR_FTP_SITE_W								MAKE_SCODE(0, 0x3A4C, PT_UNICODE)
#define PR_FTP_SITE_A								MAKE_SCODE(0, 0x3A4C, PT_STRING8)

#define PR_GENDER									MAKE_SCODE(0, 0x3A4D, PT_SHORT)

#define PR_MANAGER_NAME								MAKE_SCODE(0, 0x3A4E, PT_TSTRING)
#define PR_MANAGER_NAME_W							MAKE_SCODE(0, 0x3A4E, PT_UNICODE)
#define PR_MANAGER_NAME_A							MAKE_SCODE(0, 0x3A4E, PT_STRING8)

#define PR_NICKNAME									MAKE_SCODE(0, 0x3A4F, PT_TSTRING)
#define PR_NICKNAME_W								MAKE_SCODE(0, 0x3A4F, PT_UNICODE)
#define PR_NICKNAME_A								MAKE_SCODE(0, 0x3A4F, PT_STRING8)

#define PR_PERSONAL_HOME_PAGE						MAKE_SCODE(0, 0x3A50, PT_TSTRING)
#define PR_PERSONAL_HOME_PAGE_W						MAKE_SCODE(0, 0x3A50, PT_UNICODE)
#define PR_PERSONAL_HOME_PAGE_A						MAKE_SCODE(0, 0x3A50, PT_STRING8)


#define PR_BUSINESS_HOME_PAGE						MAKE_SCODE(0, 0x3A51, PT_TSTRING)
#define PR_BUSINESS_HOME_PAGE_W						MAKE_SCODE(0, 0x3A51, PT_UNICODE)
#define PR_BUSINESS_HOME_PAGE_A						MAKE_SCODE(0, 0x3A51, PT_STRING8)

#define PR_CONTACT_VERSION							MAKE_SCODE(0, 0x3A52, PT_CLSID)
#define PR_CONTACT_ENTRYIDS							MAKE_SCODE(0, 0x3A53, PT_MV_BINARY)

#define PR_CONTACT_ADDRTYPES						MAKE_SCODE(0, 0x3A54, PT_MV_TSTRING)
#define PR_CONTACT_ADDRTYPES_W						MAKE_SCODE(0, 0x3A54, PT_MV_UNICODE)
#define PR_CONTACT_ADDRTYPES_A						MAKE_SCODE(0, 0x3A54, PT_MV_STRING8)

#define PR_CONTACT_DEFAULT_ADDRESS_INDEX			MAKE_SCODE(0, 0x3A55, PT_LONG)

#define PR_CONTACT_EMAIL_ADDRESSES					MAKE_SCODE(0, 0x3A56, PT_MV_TSTRING)
#define PR_CONTACT_EMAIL_ADDRESSES_W				MAKE_SCODE(0, 0x3A56, PT_MV_UNICODE)
#define PR_CONTACT_EMAIL_ADDRESSES_A				MAKE_SCODE(0, 0x3A56, PT_MV_STRING8)


#define PR_COMPANY_MAIN_PHONE_NUMBER				MAKE_SCODE(0, 0x3A57, PT_TSTRING)
#define PR_COMPANY_MAIN_PHONE_NUMBER_W				MAKE_SCODE(0, 0x3A57, PT_UNICODE)
#define PR_COMPANY_MAIN_PHONE_NUMBER_A				MAKE_SCODE(0, 0x3A57, PT_STRING8)

#define PR_CHILDRENS_NAMES							MAKE_SCODE(0, 0x3A58, PT_MV_TSTRING)
#define PR_CHILDRENS_NAMES_W						MAKE_SCODE(0, 0x3A58, PT_MV_UNICODE)
#define PR_CHILDRENS_NAMES_A						MAKE_SCODE(0, 0x3A58, PT_MV_STRING8)



#define PR_HOME_ADDRESS_CITY						MAKE_SCODE(0, 0x3A59, PT_TSTRING)
#define PR_HOME_ADDRESS_CITY_W						MAKE_SCODE(0, 0x3A59, PT_UNICODE)
#define PR_HOME_ADDRESS_CITY_A						MAKE_SCODE(0, 0x3A59, PT_STRING8)

#define PR_HOME_ADDRESS_COUNTRY						MAKE_SCODE(0, 0x3A5A, PT_TSTRING)
#define PR_HOME_ADDRESS_COUNTRY_W					MAKE_SCODE(0, 0x3A5A, PT_UNICODE)
#define PR_HOME_ADDRESS_COUNTRY_A					MAKE_SCODE(0, 0x3A5A, PT_STRING8)

#define PR_HOME_ADDRESS_POSTAL_CODE					MAKE_SCODE(0, 0x3A5B, PT_TSTRING)
#define PR_HOME_ADDRESS_POSTAL_CODE_W				MAKE_SCODE(0, 0x3A5B, PT_UNICODE)
#define PR_HOME_ADDRESS_POSTAL_CODE_A				MAKE_SCODE(0, 0x3A5B, PT_STRING8)

#define PR_HOME_ADDRESS_STATE_OR_PROVINCE			MAKE_SCODE(0, 0x3A5C, PT_TSTRING)
#define PR_HOME_ADDRESS_STATE_OR_PROVINCE_W			MAKE_SCODE(0, 0x3A5C, PT_UNICODE)
#define PR_HOME_ADDRESS_STATE_OR_PROVINCE_A			MAKE_SCODE(0, 0x3A5C, PT_STRING8)

#define PR_HOME_ADDRESS_STREET						MAKE_SCODE(0, 0x3A5D, PT_TSTRING)
#define PR_HOME_ADDRESS_STREET_W					MAKE_SCODE(0, 0x3A5D, PT_UNICODE)
#define PR_HOME_ADDRESS_STREET_A					MAKE_SCODE(0, 0x3A5D, PT_STRING8)

#define PR_HOME_ADDRESS_POST_OFFICE_BOX				MAKE_SCODE(0, 0x3A5E, PT_TSTRING)
#define PR_HOME_ADDRESS_POST_OFFICE_BOX_W			MAKE_SCODE(0, 0x3A5E, PT_UNICODE)
#define PR_HOME_ADDRESS_POST_OFFICE_BOX_A			MAKE_SCODE(0, 0x3A5E, PT_STRING8)

#define PR_OTHER_ADDRESS_CITY						MAKE_SCODE(0, 0x3A5F, PT_TSTRING)
#define PR_OTHER_ADDRESS_CITY_W						MAKE_SCODE(0, 0x3A5F, PT_UNICODE)
#define PR_OTHER_ADDRESS_CITY_A						MAKE_SCODE(0, 0x3A5F, PT_STRING8)

#define PR_OTHER_ADDRESS_COUNTRY					MAKE_SCODE(0, 0x3A60, PT_TSTRING)
#define PR_OTHER_ADDRESS_COUNTRY_W					MAKE_SCODE(0, 0x3A60, PT_UNICODE)
#define PR_OTHER_ADDRESS_COUNTRY_A					MAKE_SCODE(0, 0x3A60, PT_STRING8)

#define PR_OTHER_ADDRESS_POSTAL_CODE				MAKE_SCODE(0, 0x3A61, PT_TSTRING)
#define PR_OTHER_ADDRESS_POSTAL_CODE_W				MAKE_SCODE(0, 0x3A61, PT_UNICODE)
#define PR_OTHER_ADDRESS_POSTAL_CODE_A				MAKE_SCODE(0, 0x3A61, PT_STRING8)

#define PR_OTHER_ADDRESS_STATE_OR_PROVINCE			MAKE_SCODE(0, 0x3A62, PT_TSTRING)
#define PR_OTHER_ADDRESS_STATE_OR_PROVINCE_W		MAKE_SCODE(0, 0x3A62, PT_UNICODE)
#define PR_OTHER_ADDRESS_STATE_OR_PROVINCE_A		MAKE_SCODE(0, 0x3A62, PT_STRING8)

#define PR_OTHER_ADDRESS_STREET						MAKE_SCODE(0, 0x3A63, PT_TSTRING)
#define PR_OTHER_ADDRESS_STREET_W					MAKE_SCODE(0, 0x3A63, PT_UNICODE)
#define PR_OTHER_ADDRESS_STREET_A					MAKE_SCODE(0, 0x3A63, PT_STRING8)

#define PR_OTHER_ADDRESS_POST_OFFICE_BOX			MAKE_SCODE(0, 0x3A64, PT_TSTRING)
#define PR_OTHER_ADDRESS_POST_OFFICE_BOX_W			MAKE_SCODE(0, 0x3A64, PT_UNICODE)
#define PR_OTHER_ADDRESS_POST_OFFICE_BOX_A			MAKE_SCODE(0, 0x3A64, PT_STRING8)


/*
 *	Profile section properties
 */

#define PR_STORE_PROVIDERS							MAKE_SCODE(0, 0x3D00, PT_BINARY)
#define PR_AB_PROVIDERS								MAKE_SCODE(0, 0x3D01, PT_BINARY)
#define PR_TRANSPORT_PROVIDERS						MAKE_SCODE(0, 0x3D02, PT_BINARY)

#define PR_DEFAULT_PROFILE							MAKE_SCODE(0, 0x3D04, PT_BOOLEAN)
#define PR_AB_SEARCH_PATH							MAKE_SCODE(0, 0x3D05, PT_MV_BINARY)
#define PR_AB_DEFAULT_DIR							MAKE_SCODE(0, 0x3D06, PT_BINARY)
#define PR_AB_DEFAULT_PAB							MAKE_SCODE(0, 0x3D07, PT_BINARY)

#define PR_FILTERING_HOOKS                          MAKE_SCODE(0, 0x3D08, PT_BINARY)
#define PR_SERVICE_NAME								MAKE_SCODE(0, 0x3D09, PT_TSTRING)
#define PR_SERVICE_NAME_W							MAKE_SCODE(0, 0x3D09, PT_UNICODE)
#define PR_SERVICE_NAME_A							MAKE_SCODE(0, 0x3D09, PT_STRING8)
#define PR_SERVICE_DLL_NAME							MAKE_SCODE(0, 0x3D0A, PT_TSTRING)
#define PR_SERVICE_DLL_NAME_W						MAKE_SCODE(0, 0x3D0A, PT_UNICODE)
#define PR_SERVICE_DLL_NAME_A						MAKE_SCODE(0, 0x3D0A, PT_STRING8)
#define PR_SERVICE_ENTRY_NAME						MAKE_SCODE(0, 0x3D0B, PT_STRING8)
#define PR_SERVICE_UID								MAKE_SCODE(0, 0x3D0C, PT_BINARY)
#define PR_SERVICE_EXTRA_UIDS						MAKE_SCODE(0, 0x3D0D, PT_BINARY)
#define PR_SERVICES									MAKE_SCODE(0, 0x3D0E, PT_BINARY)
#define PR_SERVICE_SUPPORT_FILES   					MAKE_SCODE(0, 0x3D0F, PT_MV_TSTRING)
#define PR_SERVICE_SUPPORT_FILES_W					MAKE_SCODE(0, 0x3D0F, PT_MV_UNICODE)
#define PR_SERVICE_SUPPORT_FILES_A					MAKE_SCODE(0, 0x3D0F, PT_MV_STRING8)
#define PR_SERVICE_DELETE_FILES   					MAKE_SCODE(0, 0x3D10, PT_MV_TSTRING)
#define PR_SERVICE_DELETE_FILES_W					MAKE_SCODE(0, 0x3D10, PT_MV_UNICODE)
#define PR_SERVICE_DELETE_FILES_A					MAKE_SCODE(0, 0x3D10, PT_MV_STRING8)
#define PR_AB_SEARCH_PATH_UPDATE   					MAKE_SCODE(0, 0x3D11, PT_BINARY)
#define PR_PROFILE_NAME								MAKE_SCODE(0, 0x3D12, PT_TSTRING)
#define PR_PROFILE_NAME_A							MAKE_SCODE(0, 0x3D12, PT_STRING8)
#define PR_PROFILE_NAME_W							MAKE_SCODE(0, 0x3D12, PT_UNICODE)

/*
 *	Status object properties
 */

#define PR_IDENTITY_DISPLAY							MAKE_SCODE(0, 0x3E00, PT_TSTRING)
#define PR_IDENTITY_DISPLAY_W						MAKE_SCODE(0, 0x3E00, PT_UNICODE)
#define PR_IDENTITY_DISPLAY_A						MAKE_SCODE(0, 0x3E00, PT_STRING8)
#define PR_IDENTITY_ENTRYID							MAKE_SCODE(0, 0x3E01, PT_BINARY)
#define PR_RESOURCE_METHODS							MAKE_SCODE(0, 0x3E02, PT_LONG)
#define PR_RESOURCE_TYPE							MAKE_SCODE(0, 0x3E03, PT_LONG)
#define PR_STATUS_CODE								MAKE_SCODE(0, 0x3E04, PT_LONG)
#define PR_IDENTITY_SEARCH_KEY						MAKE_SCODE(0, 0x3E05, PT_BINARY)
#define PR_OWN_STORE_ENTRYID						MAKE_SCODE(0, 0x3E06, PT_BINARY)
#define PR_RESOURCE_PATH							MAKE_SCODE(0, 0x3E07, PT_TSTRING)
#define PR_RESOURCE_PATH_W							MAKE_SCODE(0, 0x3E07, PT_UNICODE)
#define PR_RESOURCE_PATH_A							MAKE_SCODE(0, 0x3E07, PT_STRING8)
#define PR_STATUS_STRING							MAKE_SCODE(0, 0x3E08, PT_TSTRING)
#define PR_STATUS_STRING_W							MAKE_SCODE(0, 0x3E08, PT_UNICODE)
#define PR_STATUS_STRING_A							MAKE_SCODE(0, 0x3E08, PT_STRING8)
#define PR_X400_DEFERRED_DELIVERY_CANCEL			MAKE_SCODE(0, 0x3E09, PT_BOOLEAN)
#define PR_HEADER_FOLDER_ENTRYID					MAKE_SCODE(0, 0x3E0A, PT_BINARY)
#define PR_REMOTE_PROGRESS							MAKE_SCODE(0, 0x3E0B, PT_LONG)
#define PR_REMOTE_PROGRESS_TEXT						MAKE_SCODE(0, 0x3E0C, PT_TSTRING)
#define PR_REMOTE_PROGRESS_TEXT_W					MAKE_SCODE(0, 0x3E0C, PT_UNICODE)
#define PR_REMOTE_PROGRESS_TEXT_A					MAKE_SCODE(0, 0x3E0C, PT_STRING8)
#define PR_REMOTE_VALIDATE_OK						MAKE_SCODE(0, 0x3E0D, PT_BOOLEAN)

/*
 * Display table properties
 */

#define PR_CONTROL_FLAGS							MAKE_SCODE(0, 0x3F00, PT_LONG)
#define PR_CONTROL_STRUCTURE						MAKE_SCODE(0, 0x3F01, PT_BINARY)
#define PR_CONTROL_TYPE								MAKE_SCODE(0, 0x3F02, PT_LONG)
#define PR_DELTAX									MAKE_SCODE(0, 0x3F03, PT_LONG)
#define PR_DELTAY									MAKE_SCODE(0, 0x3F04, PT_LONG)
#define PR_XPOS										MAKE_SCODE(0, 0x3F05, PT_LONG)
#define PR_YPOS										MAKE_SCODE(0, 0x3F06, PT_LONG)
#define PR_CONTROL_ID								MAKE_SCODE(0, 0x3F07, PT_BINARY)
#define PR_INITIAL_DETAILS_PANE						MAKE_SCODE(0, 0x3F08, PT_LONG)

/*
 * Secure property id range
 */

#define PROP_ID_SECURE_MIN 							0x67F0
#define PROP_ID_SECURE_MAX 							0x67FF


#endif	/* MAPITAGS_H */

